# Generated by Django 4.0.4 on 2022-04-25 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('opt1', models.CharField(max_length=30)),
                ('opt2', models.CharField(max_length=30)),
                ('opt3', models.CharField(max_length=30)),
                ('opt1count', models.IntegerField(default=0)),
                ('opt2count', models.IntegerField(default=0)),
                ('opt3count', models.IntegerField(default=0)),
            ],
        ),
    ]
